Repository sparkdq-community/sparkdq, pull requests merged in 2025-05, with the labels that each got.

#11 feat(range-checks): add inclusive parameter to range checks
  docs/source/getting_started/checks/date/date_between_check.rst
  docs/source/getting_started/checks/date/date_max_check.rst
  docs/source/getting_started/checks/date/date_min_check.rst
  docs/source/getting_started/checks/numeric/numeric_between_check.rst
  docs/source/getting_started/checks/numeric/numeric_max_check.rst
  docs/source/getting_started/checks/numeric/numeric_min_check.rst
  docs/source/getting_started/checks/timestamp/timestamp_between_check.rst
  docs/source/getting_started/checks/timestamp/timestamp_max_check.rst
  docs/source/getting_started/checks/timestamp/timestamp_min_check.rst
  sparkdq/checks/base_classes/base_comparison_check.py
  sparkdq/checks/row_level/date_checks/date_between_check.py
  sparkdq/checks/row_level/date_checks/date_max_check.py
  sparkdq/checks/row_level/date_checks/date_min_check.py
  sparkdq/checks/row_level/numeric_checks/numeric_between_check.py
  sparkdq/checks/row_level/numeric_checks/numeric_max_check.py
  sparkdq/checks/row_level/numeric_checks/numeric_min_check.py
  sparkdq/checks/row_level/timestamp_checks/timestamp_between_check.py
  sparkdq/checks/row_level/timestamp_checks/timestamp_max_check.py
  sparkdq/checks/row_level/timestamp_checks/timestamp_min_check.py
  sparkdq/checks/utils/__init__.py
  sparkdq/checks/utils/base_comparison_check.py
  tests/unit/checks/row_level/date_checks/__init__.py
  tests/unit/checks/row_level/date_checks/test_date_between_check.py
  tests/unit/checks/row_level/date_checks/test_date_max_check.py
  tests/unit/checks/row_level/date_checks/test_date_min_check.py
  tests/unit/checks/row_level/numeric_checks/test_numeric_between_check.py
  tests/unit/checks/row_level/numeric_checks/test_numeric_max_check.py
  tests/unit/checks/row_level/numeric_checks/test_numeric_min_check.py
  tests/unit/checks/row_level/timestamp_checks/test_timestamp_between_check.py
  tests/unit/checks/row_level/timestamp_checks/test_timestamp_max_check.py
  tests/unit/checks/row_level/timestamp_checks/test_timestamp_min_check.py
Labels: enhancement

#12 docs: update documentation and docstrings
  README.md
  docs/source/api/checks.rst
  docs/source/api/core.rst
  docs/source/api/engine.rst
  docs/source/api/exceptions.rst
  docs/source/api/management.rst
  docs/source/api/plugin.rst
  docs/source/api_docs.rst
  docs/source/getting_started/checks/date/date_between_check.rst
  docs/source/getting_started/checks/date/date_max_check.rst
  docs/source/getting_started/checks/date/date_min_check.rst
  docs/source/getting_started/checks/numeric/numeric_between_check.rst
  docs/source/getting_started/checks/numeric/numeric_max_check.rst
  docs/source/getting_started/checks/numeric/numeric_min_check.rst
  docs/source/getting_started/checks/timestamp/timestamp_between_check.rst
  docs/source/getting_started/checks/timestamp/timestamp_max_check.rst
  docs/source/getting_started/checks/timestamp/timestamp_min_check.rst
  docs/source/index.rst
  sparkdq/checks/aggregate/count_checks/count_between_check.py
  sparkdq/checks/aggregate/count_checks/count_exact_check.py
  sparkdq/checks/aggregate/count_checks/count_max_check.py
  sparkdq/checks/aggregate/count_checks/count_min_check.py
  sparkdq/checks/row_level/date_checks/date_between_check.py
  sparkdq/checks/row_level/date_checks/date_min_check.py
  sparkdq/checks/row_level/null_checks/exactly_one_not_null_check.py
  sparkdq/checks/row_level/null_checks/not_null_check.py
  sparkdq/checks/row_level/null_checks/null_check.py
  sparkdq/checks/row_level/numeric_checks/numeric_between_check.py
  sparkdq/checks/row_level/numeric_checks/numeric_max_check.py
  sparkdq/checks/row_level/numeric_checks/numeric_min_check.py
  sparkdq/checks/row_level/timestamp_checks/timestamp_between_check.py
  sparkdq/checks/row_level/timestamp_checks/timestamp_min_check.py
  sparkdq/core/check_results.py
  sparkdq/core/severity.py
  sparkdq/engine/batch/dq_engine.py
  sparkdq/engine/batch/validation_result.py
  sparkdq/plugin/check_config_registry.py
  uv.lock
Labels: documentation

#36 chore(test): enable branch coverage in pyproject.toml and simplify te…
  .github/workflows/ci.yaml
  pyproject.toml
  uv.lock
Labels: chore

#38 feat: add data freshness check
  docs/source/built_in_checks/aggregate.rst
  docs/source/built_in_checks/checks/freshness/freshness_check.rst
  pyproject.toml
  sparkdq/checks/__init__.py
  sparkdq/checks/aggregate/freshness_checks/__init__.py
  sparkdq/checks/aggregate/freshness_checks/freshness_check.py
  tests/unit/checks/aggregate/freshness/__init__.py
  tests/unit/checks/aggregate/freshness/test_freshness_check.py
  uv.lock
Labels: feature request

#45 feat: update ColumnLessThanCheck to use a limit expression
  docs/source/built_in_checks/checks/columns_comparison/column_less.rst
  sparkdq/checks/row_level/columns_comparison_checks/column_less_than.py
  sparkdq/exceptions.py
  tests/unit/checks/row_level/columns_comparison_checks/test_column_less_than_check.py
Labels: enhancement, feature request

#46 chore: update examples and align documentation accordingly
  docs/source/built_in_checks/checks/columns_comparison/column_less.rst
  examples/basic-example/dq_checks.yaml
  examples/basic-example/nyc_taxi_validation_demo.ipynb
  examples/data-quality-patterns/data-quality-patterns.ipynb
  examples/data-quality-patterns/dq_checks.yaml
Labels: chore

#47 fix(deps): set minimum required Pydantic version to 2.8.0
  pyproject.toml
  uv.lock
Labels: dependencies
